[2025-01-01T06:37:58.946+0000] {processor.py:186} INFO - Started process (PID=28360) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:37:58.951+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:37:58.957+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:37:58.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:37:59.049+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:37:59.037+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:37:59.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:37:59.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.177 seconds
[2025-01-01T06:38:30.350+0000] {processor.py:186} INFO - Started process (PID=28422) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:38:30.354+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:38:30.356+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:38:30.355+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:38:30.566+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:38:30.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:38:30.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:38:30.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.254 seconds
[2025-01-01T06:39:00.905+0000] {processor.py:186} INFO - Started process (PID=28485) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:39:00.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:39:00.910+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:39:00.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:39:01.020+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:39:00.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:39:01.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:39:01.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.150 seconds
[2025-01-01T06:39:31.305+0000] {processor.py:186} INFO - Started process (PID=28548) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:39:31.306+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:39:31.307+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:39:31.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:39:31.424+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:39:31.389+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:39:31.429+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:39:31.448+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.147 seconds
[2025-01-01T06:40:01.530+0000] {processor.py:186} INFO - Started process (PID=28611) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:40:01.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:40:01.535+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:40:01.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:40:01.570+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:40:01.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:40:01.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:40:01.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.095 seconds
[2025-01-01T06:40:31.892+0000] {processor.py:186} INFO - Started process (PID=28674) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:40:31.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:40:31.897+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:40:31.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:40:31.959+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:40:31.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:40:31.990+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:40:32.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.127 seconds
[2025-01-01T06:41:02.305+0000] {processor.py:186} INFO - Started process (PID=28738) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:41:02.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:41:02.315+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:41:02.314+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:41:02.548+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:41:02.513+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:41:02.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:41:02.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.273 seconds
[2025-01-01T06:41:32.872+0000] {processor.py:186} INFO - Started process (PID=28802) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:41:32.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:41:32.876+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:41:32.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:41:32.944+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:41:32.929+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:41:32.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:41:33.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.148 seconds
[2025-01-01T06:42:03.670+0000] {processor.py:186} INFO - Started process (PID=28863) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:42:03.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:42:03.674+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:42:03.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:42:03.792+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:42:03.740+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:42:03.802+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:42:03.819+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.154 seconds
[2025-01-01T06:42:34.099+0000] {processor.py:186} INFO - Started process (PID=28927) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:42:34.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:42:34.102+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:42:34.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:42:34.164+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:42:34.150+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:42:34.168+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:42:34.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.162 seconds
[2025-01-01T06:43:04.876+0000] {processor.py:186} INFO - Started process (PID=28991) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:43:04.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:43:04.879+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:43:04.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:43:04.973+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:43:04.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:43:04.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:43:05.037+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.167 seconds
[2025-01-01T06:43:35.739+0000] {processor.py:186} INFO - Started process (PID=29055) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:43:35.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:43:35.742+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:43:35.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:43:35.824+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:43:35.811+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:43:35.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:43:35.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.190 seconds
[2025-01-01T06:44:06.216+0000] {processor.py:186} INFO - Started process (PID=29119) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:44:06.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:44:06.219+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:44:06.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:44:06.304+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:44:06.287+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:44:06.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:44:06.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.166 seconds
[2025-01-01T06:44:36.890+0000] {processor.py:186} INFO - Started process (PID=29183) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:44:36.891+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:44:36.892+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:44:36.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:44:36.924+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:44:36.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:44:36.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:44:36.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.060 seconds
[2025-01-01T06:45:07.696+0000] {processor.py:186} INFO - Started process (PID=29248) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:45:07.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:45:07.704+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:45:07.703+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:45:07.929+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:45:07.900+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:45:07.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:45:07.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.273 seconds
[2025-01-01T06:45:38.672+0000] {processor.py:186} INFO - Started process (PID=29318) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:45:38.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:45:38.675+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:45:38.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:45:38.717+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:45:38.707+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:45:38.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:45:38.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.071 seconds
[2025-01-01T06:46:08.918+0000] {processor.py:186} INFO - Started process (PID=29382) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:46:08.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:46:08.941+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:46:08.941+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:46:09.059+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:46:09.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:46:09.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:46:09.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.187 seconds
[2025-01-01T06:46:39.467+0000] {processor.py:186} INFO - Started process (PID=29446) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:46:39.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:46:39.473+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:46:39.472+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:46:39.518+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:46:39.511+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:46:39.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:46:39.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.121 seconds
[2025-01-01T06:47:09.898+0000] {processor.py:186} INFO - Started process (PID=29510) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:47:09.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:47:09.901+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:47:09.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:47:09.957+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:47:09.937+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:47:09.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:47:09.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.085 seconds
[2025-01-01T06:47:40.349+0000] {processor.py:186} INFO - Started process (PID=29574) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:47:40.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:47:40.352+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:47:40.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:47:40.426+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:47:40.410+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:47:40.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:47:40.450+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.108 seconds
[2025-01-01T06:48:12.126+0000] {processor.py:186} INFO - Started process (PID=29639) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:48:12.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:48:12.150+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:48:12.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:48:12.327+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:48:12.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:48:12.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:48:12.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.234 seconds
[2025-01-01T06:48:43.166+0000] {processor.py:186} INFO - Started process (PID=29703) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:48:43.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:48:43.179+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:48:43.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:48:43.356+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:48:43.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:48:43.365+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:48:43.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.228 seconds
[2025-01-01T06:49:14.179+0000] {processor.py:186} INFO - Started process (PID=29767) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:49:14.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:49:14.182+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:49:14.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:49:14.282+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:49:14.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:49:14.297+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:49:14.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.159 seconds
[2025-01-01T06:49:44.860+0000] {processor.py:186} INFO - Started process (PID=29830) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:49:44.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:49:44.864+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:49:44.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:49:44.910+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:49:44.900+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:49:44.915+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:49:44.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.105 seconds
[2025-01-01T06:50:15.706+0000] {processor.py:186} INFO - Started process (PID=29894) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:50:15.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:50:15.711+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:50:15.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:50:15.784+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:50:15.747+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:50:15.790+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:50:15.812+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.118 seconds
[2025-01-01T06:50:45.977+0000] {processor.py:186} INFO - Started process (PID=29958) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:50:45.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:50:45.979+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:50:45.979+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:50:46.042+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:50:46.031+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:50:46.047+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:50:46.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.182 seconds
[2025-01-01T06:51:16.485+0000] {processor.py:186} INFO - Started process (PID=30022) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:51:16.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:51:16.488+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:51:16.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:51:16.561+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:51:16.538+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:51:16.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:51:16.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.110 seconds
[2025-01-01T06:51:47.134+0000] {processor.py:186} INFO - Started process (PID=30085) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:51:47.135+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:51:47.136+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:51:47.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:51:47.248+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:51:47.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:51:47.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:51:47.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.160 seconds
[2025-01-01T06:52:17.436+0000] {processor.py:186} INFO - Started process (PID=30149) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:52:17.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:52:17.439+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:52:17.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:52:17.543+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:52:17.527+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:52:17.553+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:52:17.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.248 seconds
[2025-01-01T06:52:48.407+0000] {processor.py:186} INFO - Started process (PID=30213) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:52:48.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:52:48.415+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:52:48.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:52:48.523+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:52:48.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:52:48.527+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:52:48.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.224 seconds
[2025-01-01T06:53:18.925+0000] {processor.py:186} INFO - Started process (PID=30278) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:53:18.928+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:53:18.930+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:53:18.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:53:18.998+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:53:18.973+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:53:19.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:53:19.114+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.195 seconds
[2025-01-01T06:53:49.466+0000] {processor.py:186} INFO - Started process (PID=30342) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:53:49.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T06:53:49.470+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:53:49.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:53:49.582+0000] {logging_mixin.py:190} INFO - [2025-01-01T06:53:49.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T06:53:49.585+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T06:53:49.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.153 seconds
[2025-01-01T09:39:25.416+0000] {processor.py:186} INFO - Started process (PID=30378) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:39:25.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:39:25.419+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:39:25.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:39:25.545+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:39:25.494+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:39:25.550+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:39:25.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.165 seconds
[2025-01-01T09:39:55.919+0000] {processor.py:186} INFO - Started process (PID=30442) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:39:55.922+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:39:55.924+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:39:55.924+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:39:55.989+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:39:55.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:39:55.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:39:56.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.122 seconds
[2025-01-01T09:40:26.793+0000] {processor.py:186} INFO - Started process (PID=30507) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:40:26.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:40:26.795+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:40:26.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:40:26.841+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:40:26.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:40:26.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:40:26.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.070 seconds
[2025-01-01T09:40:57.640+0000] {processor.py:186} INFO - Started process (PID=30571) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:40:57.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:40:57.650+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:40:57.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:40:57.748+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:40:57.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:40:57.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:40:57.822+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.187 seconds
[2025-01-01T09:41:28.157+0000] {processor.py:186} INFO - Started process (PID=30635) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:41:28.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:41:28.160+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:41:28.160+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:41:28.286+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:41:28.232+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:41:28.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:41:28.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.178 seconds
[2025-01-01T09:41:58.468+0000] {processor.py:186} INFO - Started process (PID=30700) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:41:58.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:41:58.471+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:41:58.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:41:58.514+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:41:58.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:41:58.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:41:58.534+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.070 seconds
[2025-01-01T09:42:29.296+0000] {processor.py:186} INFO - Started process (PID=30762) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:42:29.298+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:42:29.299+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:42:29.299+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:42:29.506+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:42:29.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:42:29.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:42:29.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.272 seconds
[2025-01-01T09:42:59.656+0000] {processor.py:186} INFO - Started process (PID=30827) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:42:59.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:42:59.658+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:42:59.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:42:59.694+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:42:59.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:42:59.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:42:59.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.061 seconds
[2025-01-01T09:43:30.013+0000] {processor.py:186} INFO - Started process (PID=30890) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:43:30.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:43:30.015+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:43:30.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:43:30.120+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:43:30.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:43:30.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:43:30.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.147 seconds
[2025-01-01T09:44:00.395+0000] {processor.py:186} INFO - Started process (PID=30953) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:44:00.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:44:00.399+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:44:00.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:44:00.522+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:44:00.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:44:00.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:44:00.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.153 seconds
[2025-01-01T09:44:30.688+0000] {processor.py:186} INFO - Started process (PID=31018) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:44:30.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:44:30.690+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:44:30.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:44:30.794+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:44:30.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:44:30.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:44:30.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.136 seconds
[2025-01-01T09:45:01.026+0000] {processor.py:186} INFO - Started process (PID=31082) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:45:01.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:45:01.030+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:45:01.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:45:01.099+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:45:01.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:45:01.109+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:45:01.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.172 seconds
[2025-01-01T09:45:31.464+0000] {processor.py:186} INFO - Started process (PID=31146) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:45:31.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:45:31.467+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:45:31.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:45:31.536+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:45:31.521+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:45:31.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:45:31.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.150 seconds
[2025-01-01T09:46:01.734+0000] {processor.py:186} INFO - Started process (PID=31209) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:46:01.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:46:01.738+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:46:01.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:46:01.968+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:46:01.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:46:01.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:46:02.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.287 seconds
[2025-01-01T09:46:32.229+0000] {processor.py:186} INFO - Started process (PID=31273) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:46:32.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:46:32.234+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:46:32.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:46:32.499+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:46:32.462+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:46:32.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:46:32.544+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.324 seconds
[2025-01-01T09:47:03.086+0000] {processor.py:186} INFO - Started process (PID=31343) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:47:03.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:47:03.089+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:47:03.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:47:03.148+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:47:03.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:47:03.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:47:03.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.133 seconds
[2025-01-01T09:47:33.378+0000] {processor.py:186} INFO - Started process (PID=31407) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:47:33.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:47:33.381+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:47:33.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:47:33.481+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:47:33.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:47:33.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:47:33.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.164 seconds
[2025-01-01T09:48:04.079+0000] {processor.py:186} INFO - Started process (PID=31471) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:48:04.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:48:04.091+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:48:04.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:48:04.188+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:48:04.170+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:48:04.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:48:04.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.135 seconds
[2025-01-01T09:48:35.240+0000] {processor.py:186} INFO - Started process (PID=31534) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:48:35.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:48:35.243+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:48:35.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:48:35.307+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:48:35.288+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:48:35.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:48:35.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.129 seconds
[2025-01-01T09:49:05.614+0000] {processor.py:186} INFO - Started process (PID=31598) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:49:05.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:49:05.618+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:49:05.618+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:49:05.680+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:49:05.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:49:05.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:49:05.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.133 seconds
[2025-01-01T09:49:35.985+0000] {processor.py:186} INFO - Started process (PID=31662) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:49:35.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:49:35.987+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:49:35.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:49:36.112+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:49:36.087+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:49:36.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:49:36.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.167 seconds
[2025-01-01T09:50:06.698+0000] {processor.py:186} INFO - Started process (PID=31726) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:50:06.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:50:06.703+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:50:06.703+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:50:06.768+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:50:06.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:50:06.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:50:06.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.120 seconds
[2025-01-01T09:50:36.916+0000] {processor.py:186} INFO - Started process (PID=31790) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:50:36.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:50:36.932+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:50:36.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:50:36.997+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:50:36.987+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:50:37.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:50:37.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.153 seconds
[2025-01-01T09:51:07.295+0000] {processor.py:186} INFO - Started process (PID=31854) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:51:07.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:51:07.298+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:51:07.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:51:07.491+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:51:07.480+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:51:07.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:51:07.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.237 seconds
[2025-01-01T09:51:38.016+0000] {processor.py:186} INFO - Started process (PID=31918) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:51:38.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:51:38.024+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:51:38.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:51:38.135+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:51:38.124+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:51:38.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:51:38.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.157 seconds
[2025-01-01T09:52:08.507+0000] {processor.py:186} INFO - Started process (PID=31982) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:52:08.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:52:08.529+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:52:08.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:52:08.644+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:52:08.626+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:52:08.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:52:08.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.168 seconds
[2025-01-01T09:52:39.454+0000] {processor.py:186} INFO - Started process (PID=32046) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:52:39.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T09:52:39.457+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:52:39.457+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:52:39.530+0000] {logging_mixin.py:190} INFO - [2025-01-01T09:52:39.513+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T09:52:39.537+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T09:52:39.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.107 seconds
[2025-01-01T13:56:17.562+0000] {processor.py:186} INFO - Started process (PID=32050) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:56:17.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T13:56:17.564+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:56:17.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:56:17.621+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:56:17.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T13:56:17.625+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:56:17.640+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.083 seconds
[2025-01-01T13:56:48.651+0000] {processor.py:186} INFO - Started process (PID=32114) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:56:48.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T13:56:48.665+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:56:48.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:56:48.773+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:56:48.756+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T13:56:48.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:56:48.817+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.173 seconds
[2025-01-01T13:57:18.954+0000] {processor.py:186} INFO - Started process (PID=32178) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:57:18.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T13:57:18.956+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:57:18.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:57:19.014+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:57:19.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T13:57:19.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:57:19.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.101 seconds
[2025-01-01T13:57:49.880+0000] {processor.py:186} INFO - Started process (PID=32242) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:57:49.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T13:57:49.885+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:57:49.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:57:49.956+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:57:49.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T13:57:49.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:57:49.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.105 seconds
[2025-01-01T13:58:20.682+0000] {processor.py:186} INFO - Started process (PID=32306) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:58:20.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T13:58:20.686+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:58:20.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:58:20.806+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:58:20.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T13:58:20.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:58:20.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.166 seconds
[2025-01-01T13:58:51.539+0000] {processor.py:186} INFO - Started process (PID=32369) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:58:51.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T13:58:51.544+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:58:51.543+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:58:51.631+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:58:51.612+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T13:58:51.639+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:58:51.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.129 seconds
[2025-01-01T13:59:21.994+0000] {processor.py:186} INFO - Started process (PID=32433) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:59:21.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T13:59:21.998+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:59:21.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:59:22.578+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:59:22.474+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T13:59:22.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:59:22.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.660 seconds
[2025-01-01T13:59:52.940+0000] {processor.py:186} INFO - Started process (PID=32498) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:59:52.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T13:59:52.943+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:59:52.943+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:59:53.013+0000] {logging_mixin.py:190} INFO - [2025-01-01T13:59:52.998+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T13:59:53.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T13:59:53.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.151 seconds
[2025-01-01T14:00:23.244+0000] {processor.py:186} INFO - Started process (PID=32561) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:00:23.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:00:23.246+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:00:23.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:00:23.292+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:00:23.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:00:23.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:00:23.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.069 seconds
[2025-01-01T14:00:53.521+0000] {processor.py:186} INFO - Started process (PID=32625) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:00:53.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:00:53.531+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:00:53.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:00:53.790+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:00:53.753+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:00:53.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:00:53.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.361 seconds
[2025-01-01T14:01:24.127+0000] {processor.py:186} INFO - Started process (PID=32689) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:01:24.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:01:24.129+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:01:24.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:01:24.194+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:01:24.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:01:24.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:01:24.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.124 seconds
[2025-01-01T14:01:54.454+0000] {processor.py:186} INFO - Started process (PID=32753) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:01:54.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:01:54.458+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:01:54.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:01:54.540+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:01:54.520+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:01:54.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:01:54.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.112 seconds
[2025-01-01T14:02:24.997+0000] {processor.py:186} INFO - Started process (PID=32817) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:02:24.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:02:25.000+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:02:25.000+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:02:25.087+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:02:25.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:02:25.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:02:25.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.120 seconds
[2025-01-01T14:02:55.317+0000] {processor.py:186} INFO - Started process (PID=32880) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:02:55.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:02:55.319+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:02:55.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:02:55.387+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:02:55.370+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:02:55.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:02:55.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.099 seconds
[2025-01-01T14:03:26.211+0000] {processor.py:186} INFO - Started process (PID=32944) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:03:26.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:03:26.213+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:03:26.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:03:26.369+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:03:26.362+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:03:26.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:03:26.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.223 seconds
[2025-01-01T14:03:57.250+0000] {processor.py:186} INFO - Started process (PID=33007) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:03:57.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:03:57.252+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:03:57.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:03:57.563+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:03:57.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:03:57.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:03:57.585+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.340 seconds
[2025-01-01T14:04:27.877+0000] {processor.py:186} INFO - Started process (PID=33072) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:04:27.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:04:27.880+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:04:27.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:04:27.925+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:04:27.914+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:04:27.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:04:27.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.128 seconds
[2025-01-01T14:04:58.144+0000] {processor.py:186} INFO - Started process (PID=33135) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:04:58.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:04:58.147+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:04:58.146+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:04:58.246+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:04:58.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:04:58.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:04:58.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.147 seconds
[2025-01-01T14:05:28.491+0000] {processor.py:186} INFO - Started process (PID=33198) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:05:28.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:05:28.495+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:05:28.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:05:28.568+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:05:28.548+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:05:28.574+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:05:28.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.116 seconds
[2025-01-01T14:05:59.325+0000] {processor.py:186} INFO - Started process (PID=33262) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:05:59.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:05:59.329+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:05:59.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:05:59.387+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:05:59.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:05:59.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:05:59.434+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.115 seconds
[2025-01-01T14:06:58.676+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:06:58.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:06:58.682+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:06:58.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:06:58.742+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:06:58.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:06:58.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:06:58.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.098 seconds
[2025-01-01T14:07:29.678+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:07:29.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:07:29.682+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:07:29.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:07:29.725+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:07:29.710+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:07:29.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:07:29.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.080 seconds
[2025-01-01T14:08:00.649+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:08:00.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:08:00.655+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:08:00.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:08:00.713+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:08:00.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:08:00.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:08:00.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.119 seconds
[2025-01-01T14:08:30.899+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:08:30.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:08:30.905+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:08:30.905+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:08:30.981+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:08:30.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:08:30.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:08:31.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.113 seconds
[2025-01-01T14:09:01.583+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:09:01.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:09:01.589+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:09:01.589+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:09:01.711+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:09:01.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:09:01.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:09:01.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.197 seconds
[2025-01-01T14:09:32.202+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:09:32.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:09:32.209+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:09:32.208+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:09:32.380+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:09:32.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:09:32.383+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:09:32.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.224 seconds
[2025-01-01T14:10:03.321+0000] {processor.py:186} INFO - Started process (PID=459) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:10:03.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:10:03.325+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:10:03.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:10:03.370+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:10:03.366+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:10:03.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:10:03.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.108 seconds
[2025-01-01T14:10:33.601+0000] {processor.py:186} INFO - Started process (PID=523) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:10:33.603+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:10:33.606+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:10:33.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:10:33.662+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:10:33.648+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:10:33.665+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:10:33.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.140 seconds
[2025-01-01T14:11:04.009+0000] {processor.py:186} INFO - Started process (PID=587) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:11:04.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:11:04.016+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:11:04.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:11:04.119+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:11:04.105+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:11:04.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:11:04.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.185 seconds
[2025-01-01T14:11:34.986+0000] {processor.py:186} INFO - Started process (PID=651) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:11:34.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:11:34.994+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:11:34.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:11:35.085+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:11:35.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:11:35.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:11:35.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.135 seconds
[2025-01-01T14:12:05.833+0000] {processor.py:186} INFO - Started process (PID=715) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:12:05.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:12:05.841+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:12:05.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:12:06.199+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:12:06.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:12:06.204+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:12:06.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.424 seconds
[2025-01-01T14:12:36.635+0000] {processor.py:186} INFO - Started process (PID=779) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:12:36.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:12:36.639+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:12:36.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:12:36.695+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:12:36.683+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:12:36.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:12:36.746+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.117 seconds
[2025-01-01T14:13:07.112+0000] {processor.py:186} INFO - Started process (PID=843) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:13:07.117+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:13:07.126+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:13:07.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:13:07.303+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:13:07.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:13:07.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:13:07.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.274 seconds
[2025-01-01T14:13:38.155+0000] {processor.py:186} INFO - Started process (PID=907) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:13:38.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:13:38.166+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:13:38.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:13:38.270+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:13:38.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:13:38.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:13:38.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.198 seconds
[2025-01-01T14:14:08.477+0000] {processor.py:186} INFO - Started process (PID=971) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:14:08.479+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:14:08.483+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:14:08.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:14:08.550+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:14:08.539+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:14:08.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:14:08.615+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.146 seconds
[2025-01-01T14:14:39.143+0000] {processor.py:186} INFO - Started process (PID=1034) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:14:39.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:14:39.146+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:14:39.146+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:14:39.240+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:14:39.222+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:14:39.246+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:14:39.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.135 seconds
[2025-01-01T14:15:09.886+0000] {processor.py:186} INFO - Started process (PID=1099) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:15:09.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:15:09.890+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:15:09.889+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:15:09.926+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:15:09.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:15:09.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:15:09.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.065 seconds
[2025-01-01T14:15:40.254+0000] {processor.py:186} INFO - Started process (PID=1163) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:15:40.261+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:15:40.265+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:15:40.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:15:40.340+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:15:40.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:15:40.343+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:15:40.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.126 seconds
[2025-01-01T14:16:11.311+0000] {processor.py:186} INFO - Started process (PID=1227) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:16:11.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:16:11.314+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:16:11.314+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:16:11.363+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:16:11.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:16:11.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:16:11.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.078 seconds
[2025-01-01T14:16:41.558+0000] {processor.py:186} INFO - Started process (PID=1291) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:16:41.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:16:41.566+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:16:41.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:16:41.692+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:16:41.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:16:41.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:16:41.732+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.179 seconds
[2025-01-01T14:17:11.958+0000] {processor.py:186} INFO - Started process (PID=1355) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:17:11.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:17:11.963+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:17:11.963+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:17:12.031+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:17:12.017+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:17:12.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:17:12.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.125 seconds
[2025-01-01T14:17:42.786+0000] {processor.py:186} INFO - Started process (PID=1419) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:17:42.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:17:42.791+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:17:42.791+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:17:42.873+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:17:42.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:17:42.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:17:42.916+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.134 seconds
[2025-01-01T14:18:13.670+0000] {processor.py:186} INFO - Started process (PID=1483) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:18:13.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:18:13.674+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:18:13.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:18:13.734+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:18:13.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:18:13.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:18:13.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.106 seconds
[2025-01-01T14:18:44.284+0000] {processor.py:186} INFO - Started process (PID=1547) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:18:44.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:18:44.313+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:18:44.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:18:44.538+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:18:44.477+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:18:44.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:18:44.564+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.288 seconds
[2025-01-01T14:19:14.851+0000] {processor.py:186} INFO - Started process (PID=1611) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:19:14.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:19:14.855+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:19:14.854+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:19:14.940+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:19:14.925+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:19:14.945+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:19:14.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.122 seconds
[2025-01-01T14:19:45.268+0000] {processor.py:186} INFO - Started process (PID=1675) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:19:45.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:19:45.272+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:19:45.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:19:45.345+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:19:45.334+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:19:45.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:19:45.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.108 seconds
[2025-01-01T14:20:15.612+0000] {processor.py:186} INFO - Started process (PID=1738) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:20:15.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:20:15.621+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:20:15.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:20:15.674+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:20:15.660+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:20:15.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:20:15.734+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.134 seconds
[2025-01-01T14:20:46.291+0000] {processor.py:186} INFO - Started process (PID=1802) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:20:46.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:20:46.297+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:20:46.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:20:46.370+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:20:46.355+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:20:46.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:20:46.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.188 seconds
[2025-01-01T14:21:17.099+0000] {processor.py:186} INFO - Started process (PID=1866) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:21:17.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:21:17.104+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:21:17.104+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:21:17.178+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:21:17.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:21:17.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:21:17.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.122 seconds
[2025-01-01T14:21:47.536+0000] {processor.py:186} INFO - Started process (PID=1930) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:21:47.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:21:47.541+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:21:47.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:21:47.608+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:21:47.592+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:21:47.613+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:21:47.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.117 seconds
[2025-01-01T14:22:17.784+0000] {processor.py:186} INFO - Started process (PID=1994) to work on /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:22:17.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2025-01-01T14:22:17.789+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:22:17.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:22:17.854+0000] {logging_mixin.py:190} INFO - [2025-01-01T14:22:17.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2025-01-01T14:22:17.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2025-01-01T14:22:17.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.109 seconds
