[2024-12-30T18:54:41.932+0000] {processor.py:186} INFO - Started process (PID=690) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:54:41.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T18:54:41.936+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:54:41.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:54:42.010+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:54:41.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T18:54:42.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:54:42.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.152 seconds
[2024-12-30T18:55:12.692+0000] {processor.py:186} INFO - Started process (PID=748) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:55:12.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T18:55:12.695+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:55:12.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:55:12.816+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:55:12.802+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T18:55:12.822+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:55:12.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.159 seconds
[2024-12-30T18:55:43.226+0000] {processor.py:186} INFO - Started process (PID=812) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:55:43.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T18:55:43.231+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:55:43.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:55:43.339+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:55:43.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T18:55:43.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:55:43.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.189 seconds
[2024-12-30T18:56:13.695+0000] {processor.py:186} INFO - Started process (PID=876) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:56:13.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T18:56:13.702+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:56:13.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:56:13.812+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:56:13.792+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T18:56:13.818+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:56:13.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.193 seconds
[2024-12-30T18:56:44.914+0000] {processor.py:186} INFO - Started process (PID=940) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:56:44.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T18:56:44.919+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:56:44.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:56:45.006+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:56:44.988+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T18:56:45.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:56:45.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.163 seconds
[2024-12-30T18:57:15.864+0000] {processor.py:186} INFO - Started process (PID=1004) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:57:15.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T18:57:15.869+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:57:15.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:57:15.930+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:57:15.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T18:57:15.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:57:15.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.137 seconds
[2024-12-30T18:57:46.080+0000] {processor.py:186} INFO - Started process (PID=1068) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:57:46.081+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T18:57:46.086+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:57:46.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:57:46.158+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:57:46.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T18:57:46.162+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:57:46.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.145 seconds
[2024-12-30T18:58:16.433+0000] {processor.py:186} INFO - Started process (PID=1132) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:58:16.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T18:58:16.436+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:58:16.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:58:16.637+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:58:16.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T18:58:16.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:58:16.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.283 seconds
[2024-12-30T18:58:47.337+0000] {processor.py:186} INFO - Started process (PID=1190) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:58:47.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T18:58:47.340+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:58:47.340+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:58:47.375+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:58:47.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T18:58:47.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:58:47.428+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.096 seconds
[2024-12-30T18:59:28.125+0000] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:59:28.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T18:59:28.128+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:59:28.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:59:28.194+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:59:28.181+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T18:59:28.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:59:28.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.101 seconds
[2024-12-30T18:59:59.017+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:59:59.018+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T18:59:59.020+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:59:59.020+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:59:59.074+0000] {logging_mixin.py:190} INFO - [2024-12-30T18:59:59.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T18:59:59.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T18:59:59.144+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.129 seconds
[2024-12-30T19:00:29.994+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:00:29.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:00:29.998+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:00:29.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:00:30.024+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:00:30.020+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:00:30.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:00:30.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.087 seconds
[2024-12-30T19:01:09.355+0000] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:01:09.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:01:09.368+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:01:09.368+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:01:09.424+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:01:09.413+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:01:09.427+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:01:09.454+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.105 seconds
[2024-12-30T19:01:40.223+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:01:40.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:01:40.227+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:01:40.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:01:40.293+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:01:40.285+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:01:40.296+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:01:40.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.125 seconds
[2024-12-30T19:02:11.286+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:02:11.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:02:11.289+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:02:11.289+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:02:11.349+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:02:11.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:02:11.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:02:11.415+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.134 seconds
[2024-12-30T19:02:42.185+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:02:42.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:02:42.189+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:02:42.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:02:42.396+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:02:42.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:02:42.421+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:02:42.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.259 seconds
[2024-12-30T19:03:13.045+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:03:13.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:03:13.050+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:03:13.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:03:13.170+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:03:13.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:03:13.175+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:03:13.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.162 seconds
[2024-12-30T19:03:43.317+0000] {processor.py:186} INFO - Started process (PID=380) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:03:43.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:03:43.324+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:03:43.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:03:43.392+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:03:43.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:03:43.398+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:03:43.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.113 seconds
[2024-12-30T19:04:13.541+0000] {processor.py:186} INFO - Started process (PID=444) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:04:13.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:04:13.550+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:04:13.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:04:13.611+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:04:13.603+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:04:13.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:04:13.631+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.094 seconds
[2024-12-30T19:04:43.870+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:04:43.871+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:04:43.873+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:04:43.873+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:04:43.932+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:04:43.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:04:43.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:04:43.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.108 seconds
[2024-12-30T19:05:14.609+0000] {processor.py:186} INFO - Started process (PID=571) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:05:14.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:05:14.613+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:05:14.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:05:14.775+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:05:14.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:05:14.780+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:05:14.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.196 seconds
[2024-12-30T19:05:44.871+0000] {processor.py:186} INFO - Started process (PID=635) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:05:44.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:05:44.875+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:05:44.875+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:05:47.180+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:05:47.047+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:05:47.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:05:47.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.254 seconds
[2024-12-30T19:06:20.600+0000] {processor.py:186} INFO - Started process (PID=699) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:06:20.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:06:20.621+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:06:20.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:06:20.779+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:06:20.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:06:20.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:06:20.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.227 seconds
[2024-12-30T19:06:51.336+0000] {processor.py:186} INFO - Started process (PID=763) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:06:51.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:06:51.342+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:06:51.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:06:51.407+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:06:51.393+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:06:51.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:06:51.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.127 seconds
[2024-12-30T19:07:25.268+0000] {processor.py:186} INFO - Started process (PID=55) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:07:25.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:07:25.275+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:07:25.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:07:25.346+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:07:25.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:07:25.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:07:25.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.098 seconds
[2024-12-30T19:07:57.954+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:07:57.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:07:57.958+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:07:57.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:07:58.034+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:07:58.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:07:58.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:07:58.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.140 seconds
[2024-12-30T19:08:30.481+0000] {processor.py:186} INFO - Started process (PID=183) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:08:30.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:08:30.486+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:08:30.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:08:30.615+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:08:30.574+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:08:30.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:08:30.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.169 seconds
[2024-12-30T19:09:03.106+0000] {processor.py:186} INFO - Started process (PID=247) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:09:03.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:09:03.109+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:09:03.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:09:03.142+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:09:03.135+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:09:03.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:09:03.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.093 seconds
[2024-12-30T19:09:35.876+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:09:35.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:09:35.879+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:09:35.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:09:35.933+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:09:35.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:09:35.938+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:09:35.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.081 seconds
[2024-12-30T19:10:08.708+0000] {processor.py:186} INFO - Started process (PID=375) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:10:08.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:10:08.712+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:10:08.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:10:08.773+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:10:08.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:10:08.777+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:10:08.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.102 seconds
[2024-12-30T19:10:41.373+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:10:41.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:10:41.390+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:10:41.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:10:41.888+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:10:41.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:10:41.892+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:10:41.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.580 seconds
[2024-12-30T19:11:13.885+0000] {processor.py:186} INFO - Started process (PID=503) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:11:13.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:11:13.892+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:11:13.891+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:11:13.969+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:11:13.955+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:11:13.976+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:11:13.997+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.116 seconds
[2024-12-30T19:11:46.362+0000] {processor.py:186} INFO - Started process (PID=567) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:11:46.364+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:11:46.368+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:11:46.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:11:46.470+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:11:46.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:11:46.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:11:46.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.151 seconds
[2024-12-30T19:12:18.860+0000] {processor.py:186} INFO - Started process (PID=631) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:12:18.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:12:18.865+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:12:18.865+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:12:18.939+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:12:18.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:12:18.941+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:12:19.010+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.161 seconds
[2024-12-30T19:12:51.362+0000] {processor.py:186} INFO - Started process (PID=695) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:12:51.364+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:12:51.367+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:12:51.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:12:51.430+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:12:51.417+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:12:51.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:12:51.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.095 seconds
[2024-12-30T19:13:23.700+0000] {processor.py:186} INFO - Started process (PID=759) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:13:23.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:13:23.705+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:13:23.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:13:23.770+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:13:23.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:13:23.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:13:23.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.108 seconds
[2024-12-30T19:13:57.315+0000] {processor.py:186} INFO - Started process (PID=823) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:13:57.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:13:57.322+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:13:57.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:13:57.367+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:13:57.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:13:57.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:13:57.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.116 seconds
[2024-12-30T19:14:27.562+0000] {processor.py:186} INFO - Started process (PID=887) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:14:27.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:14:27.569+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:14:27.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:14:27.760+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:14:27.674+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:14:27.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:14:27.833+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.275 seconds
[2024-12-30T19:14:58.270+0000] {processor.py:186} INFO - Started process (PID=951) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:14:58.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:14:58.274+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:14:58.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:14:58.337+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:14:58.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:14:58.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:14:58.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.102 seconds
[2024-12-30T19:15:29.448+0000] {processor.py:186} INFO - Started process (PID=1015) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:15:29.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:15:29.454+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:15:29.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:15:29.605+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:15:29.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:15:29.610+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:15:29.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.229 seconds
[2024-12-30T19:16:02.029+0000] {processor.py:186} INFO - Started process (PID=1080) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:16:02.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:16:02.042+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:16:02.042+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:16:02.119+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:16:02.107+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:16:02.123+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:16:02.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.129 seconds
[2024-12-30T19:16:32.388+0000] {processor.py:186} INFO - Started process (PID=1144) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:16:32.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:16:32.393+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:16:32.393+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:16:32.454+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:16:32.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:16:32.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:16:34.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.101 seconds
[2024-12-30T19:17:12.205+0000] {processor.py:186} INFO - Started process (PID=60) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:17:12.209+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:17:12.213+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:17:12.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:17:12.292+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:17:12.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:17:12.297+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:17:12.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.154 seconds
[2024-12-30T19:17:42.646+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:17:42.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:17:42.648+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:17:42.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:17:42.801+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:17:42.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:17:42.805+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:17:42.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.179 seconds
[2024-12-30T19:18:13.557+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:18:13.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:18:13.560+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:18:13.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:18:13.658+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:18:13.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:18:13.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:18:13.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.125 seconds
[2024-12-30T19:18:45.163+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:18:45.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:18:45.167+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:18:45.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:18:45.236+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:18:45.223+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:18:45.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:18:45.256+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.098 seconds
[2024-12-30T19:19:17.026+0000] {processor.py:186} INFO - Started process (PID=316) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:19:17.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:19:17.030+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:19:17.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:19:17.101+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:19:17.086+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:19:17.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:19:17.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.195 seconds
[2024-12-30T19:19:49.644+0000] {processor.py:186} INFO - Started process (PID=380) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:19:49.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:19:49.649+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:19:49.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:19:49.703+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:19:49.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:19:49.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:19:49.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.100 seconds
[2024-12-30T19:20:22.298+0000] {processor.py:186} INFO - Started process (PID=444) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:20:22.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:20:22.303+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:20:22.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:20:22.372+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:20:22.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:20:22.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:20:22.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.117 seconds
[2024-12-30T19:20:55.685+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:20:55.686+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:20:55.688+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:20:55.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:20:55.720+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:20:55.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:20:55.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:20:55.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.099 seconds
[2024-12-30T19:21:28.708+0000] {processor.py:186} INFO - Started process (PID=572) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:21:28.738+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:21:28.742+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:21:28.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:21:28.793+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:21:28.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:21:28.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:21:28.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.114 seconds
[2024-12-30T19:22:00.722+0000] {processor.py:186} INFO - Started process (PID=636) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:22:00.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:22:00.729+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:22:00.728+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:22:00.795+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:22:00.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:22:00.833+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:22:00.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.146 seconds
[2024-12-30T19:22:33.516+0000] {processor.py:186} INFO - Started process (PID=700) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:22:33.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:22:33.523+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:22:33.522+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:22:33.740+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:22:33.699+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:22:33.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:22:33.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.282 seconds
[2024-12-30T19:23:06.497+0000] {processor.py:186} INFO - Started process (PID=764) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:23:06.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:23:06.501+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:23:06.501+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:23:06.749+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:23:06.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:23:06.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:23:06.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.325 seconds
[2024-12-30T19:23:39.253+0000] {processor.py:186} INFO - Started process (PID=828) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:23:39.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:23:39.257+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:23:39.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:23:39.326+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:23:39.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:23:39.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:23:39.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.177 seconds
[2024-12-30T19:24:12.493+0000] {processor.py:186} INFO - Started process (PID=892) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:24:12.495+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:24:12.498+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:24:12.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:24:12.565+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:24:12.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:24:12.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:24:12.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.118 seconds
[2024-12-30T19:24:45.126+0000] {processor.py:186} INFO - Started process (PID=956) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:24:45.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:24:45.132+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:24:45.131+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:24:45.210+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:24:45.188+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:24:45.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:24:45.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.124 seconds
[2024-12-30T19:25:18.093+0000] {processor.py:186} INFO - Started process (PID=1020) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:25:18.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:25:18.096+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:25:18.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:25:18.182+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:25:18.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:25:18.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:25:18.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.121 seconds
[2024-12-30T19:25:50.355+0000] {processor.py:186} INFO - Started process (PID=1083) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:25:50.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:25:50.358+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:25:50.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:25:50.406+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:25:50.399+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:25:50.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:25:50.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.082 seconds
[2024-12-30T19:26:20.765+0000] {processor.py:186} INFO - Started process (PID=1147) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:26:22.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:26:22.920+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:26:22.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:26:22.975+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:26:22.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:26:22.978+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:26:23.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.160 seconds
[2024-12-30T19:26:55.762+0000] {processor.py:186} INFO - Started process (PID=1211) to work on /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:26:55.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2024-12-30T19:26:55.767+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:26:55.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:26:55.849+0000] {logging_mixin.py:190} INFO - [2024-12-30T19:26:55.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 4, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2024-12-30T19:26:55.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2024-12-30T19:26:55.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.132 seconds
